# Netlify configuration file
[build]
  # Directory where Netlify runs the build command
  base = "."
  
  # Build command with Prisma generation
  command = "npm run build:netlify"
  
  # Directory to publish (output directory)
  publish = ".next"
  
  # Functions directory for serverless functions
  functions = "netlify/functions"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Next.js specific settings
  NEXT_TELEMETRY_DISABLED = "1"
  
  # Build optimization
  NPM_FLAGS = "--production=false"

# Redirects and rewrites for Next.js App Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Runtime for Next.js 15
[functions]
  node_bundler = "esbuild"
