/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // USS Brasil Brand Colors - Design System
        'brand-blue': {
          DEFAULT: '#034a6e',
          50: '#f0f7fb',
          100: '#e1eff7',
          200: '#c3dfef',
          300: '#a5cfe7',
          400: '#87bfdf',
          500: '#06618f',
          600: '#034a6e',
          700: '#02415c',
          800: '#02374f',
          900: '#02344f',
        },
        'brand-cyan': {
          DEFAULT: '#54c4cf',
          50: '#f0fcfd',
          100: '#e1f9fb',
          200: '#c3f3f7',
          300: '#a5edf3',
          400: '#87e7ef',
          500: '#54c4cf',
          600: '#42a0a8',
          700: '#377c81',
          800: '#2c585a',
          900: '#213433',
        },
        'brand-gold': {
          DEFAULT: '#d4af37',
          50: '#fdfbf4',
          100: '#fbf7e9',
          200: '#f7efd3',
          300: '#f3e7bd',
          400: '#efdfa7',
          500: '#d4af37',
          600: '#b8992f',
          700: '#9c8327',
          800: '#806d1f',
          900: '#645717',
        },
        // Neutrals
        'bg-light': '#f5f7fa',
        'bg-dark': '#0d1b22',
        'text-dark': '#1a1a1a',
        'muted': '#bdbdbd',
        // Legacy support (mantém compatibilidade)
        'uss-primary': {
          DEFAULT: '#034a6e',
          light: '#06618f',
          dark: '#02344f',
        },
        'uss-secondary': {
          DEFAULT: '#54c4cf',
          light: '#6fd4dc',
          dark: '#3ea0a8',
        },
        'uss-gray': {
          900: '#1a1a1a',
          700: '#2d2d2d',
          500: '#6e6e6e',
          300: '#bdbdbd',
        },
        'uss-success': '#28a745',
        'uss-warning': '#ffc107',
        'uss-error': '#dc3545',
        'uss-info': '#17a2b8',
        'uss-off-white': '#f8f9fa',
      },
      backgroundImage: {
        'gradient-uss-primary': 'linear-gradient(135deg, #034a6e, #06618f)',
        'gradient-uss-secondary': 'linear-gradient(135deg, #54c4cf, #6fd4dc)',
        'gradient-uss-brand': 'linear-gradient(135deg, #034a6e, #54c4cf)',
        'gradient-brand-blue': 'linear-gradient(135deg, var(--brand-blue-600), var(--brand-blue-500))',
        'gradient-brand-cyan': 'linear-gradient(135deg, var(--brand-cyan-500), var(--brand-cyan-400))',
        'gradient-brand': 'linear-gradient(135deg, var(--brand-blue-600), var(--brand-cyan-500))',
        'gradient-vip': 'linear-gradient(135deg, var(--brand-gold-500), var(--brand-gold-400))',
      },
      fontSize: {
        'xs': ['0.75rem', { lineHeight: '1rem' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'base': ['1rem', { lineHeight: '1.5rem' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'xl': ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1' }],
        '6xl': ['3.75rem', { lineHeight: '1' }],
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '128': '32rem',
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
