import { Product } from '../types/index'
import { ProductStatus } from '@prisma/client'

export const brandProducts: Record<string, Product[]> = {
  apple: [
    {
      id: 'apple-iphone-16-pro',
      name: 'iPhone 16 Pro',
      slug: 'iphone-16-pro',
      classe: 'Smartphone',
      categoria: 'Apple',
      price: 10499,
      rating: 5,
      reviews: 120,
      totalReviews: 120,
      isNew: true,
      isFeatured: true,
      discount: 0,
      description: 'O novo iPhone 16 Pro com design inovador.',
      features: ['Tela OLED', 'Câmera tripla', 'Face ID'],
      images: { main: '/products/Iphone 16 Pro.png' },
      colors: ['Preto', 'Prata'],
      specifications: {},
      stock: 10,
      status: ProductStatus.ACTIVE,
      tags: ['smartphone', 'apple'],
      createdAt: '',
      updatedAt: ''
    },
    {
      id: 'apple-macbook-pro',
      name: 'MacBook Pro',
      slug: 'macbook-pro',
      classe: 'Notebook',
      categoria: 'Apple',
      price: 19999,
      rating: 5,
      reviews: 80,
      totalReviews: 80,
      isNew: false,
      isFeatured: true,
      discount: 0,
      description: 'MacBook Pro com chip M2.',
      features: ['Chip M2', 'Tela Retina', 'Touch Bar'],
      images: { main: '/products/Macbook Pro.png' },
      colors: ['Cinza', 'Prata'],
      specifications: {},
      stock: 5,
      status: ProductStatus.ACTIVE,
      tags: ['notebook', 'apple'],
      createdAt: '',
      updatedAt: ''
    },
    {
      id: 'apple-ipad-pro',
      name: 'iPad Pro',
      slug: 'ipad-pro',
      classe: 'Tablet',
      categoria: 'Apple',
      price: 10999,
      rating: 5,
      reviews: 60,
      totalReviews: 60,
      isNew: false,
      isFeatured: true,
      discount: 0,
      description: 'iPad Pro com tela Liquid Retina.',
      features: ['Tela Liquid Retina', 'Face ID'],
      images: { main: '/products/Ipad Pro.png' },
      colors: ['Prata'],
      specifications: {},
      stock: 8,
      status: ProductStatus.ACTIVE,
      tags: ['tablet', 'apple'],
      createdAt: '',
      updatedAt: ''
    },
    {
      id: 'apple-watch-series-10',
      name: 'Apple Watch Series 10',
      slug: 'watch-series-10',
      classe: 'Acessorio',
      categoria: 'Apple',
      price: 6999,
      rating: 5,
      reviews: 40,
      totalReviews: 40,
      isNew: true,
      isFeatured: false,
      discount: 0,
      description: 'Apple Watch Series 10 com novos sensores.',
      features: ['Sensor cardíaco', 'GPS'],
      images: { main: '/products/Watch Series 10.png' },
      colors: ['Preto'],
      specifications: {},
      stock: 12,
      status: ProductStatus.ACTIVE,
      tags: ['acessorio', 'apple'],
      createdAt: '',
      updatedAt: ''
    }
  ]
  // Adicione outras marcas conforme necessário
}
